### ISSUE TITLE
demo.py  RuntimeError 

### ISSUE THREAD

**Issue by skyundead** [foamliu/Image-Captioning-v2#16]
Traceback (most recent call last):
  File "demo.py", line 234, in <module>
    seq, alphas = caption_image_beam_search(encoder, decoder, img, word_map, args.beam_size)
  File "demo.py", line 97, in caption_image_beam_search
    awe, alpha = decoder.attention(encoder_out, h)  # (s, encoder_dim), (s, num_pixels)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\study\torch_study\chinese\models.py", line 78, in forward
    att2 = self.decoder_att(decoder_hidden)  # (batch_size, attention_dim)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\anaconda\lib\site-packages\torch\nn\functional.py", line 1369, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by foamliu** [comment]
Seems your CUDA was not installed successfully.
